# Generated by Django 4.0.4 on 2022-05-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feautred_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feautred_image',
            new_name='featured_image',
        ),
    ]
